QWEN_API_KEY: "sk-xxxx"  # Replace with your Qwen API key
QWEN_BASE_URL: "https://dashscope.aliyuncs.com/compatible-mode/v1"
QWEN_API_MODEL_NAME: "qwen3-32b"
DEEPSEEK_API_KEY: "sk-xxxx"  # Replace with your Deepseek API key
DEEPSEEK_BASE_URL: "https://api.deepseek.com"
DEEPSEEK_API_MODEL_NAME: "deepseek-chat"
